const list = [
    {
      id: 1,
      title: "O livro que você gostaria que seus pais tivessem lido ",
      author: "  by Philippa Perry | 28 Fevereiro 2020",
      price: 89,
      img: "https://m.media-amazon.com/images/I/71BROqAwZtL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "A Biblioteca da Meia-Noite",
      author: "by Matt Haig | 20 Setembro 2021",
      price: 98,
      img: "https://m.media-amazon.com/images/I/81flXGbA6-L._SY425_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "As coisas que você só vê quando desacelera",
      author: "by Haemin Sunim | 27 setembro 2017",
      price: 143,
      img: "https://m.media-amazon.com/images/I/61OEg3V-FTL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "A princesa salva a si mesma neste livro",
      author: "by  Amanda Lovelace  |  30 Novembro 2017",
      price: 57,
      img: "https://m.media-amazon.com/images/I/61l3pp4owJL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Hábitos atômicos",
      author: "by  James Clear | 8 Agosto 2019",
      price: 149,
      img: "https://m.media-amazon.com/images/I/61sJSnwPFaS._SY425_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "#umdiasemreclamar: Descubra por que a gratidão pode mudar a sua vida",
      author: "by  Davi Lago | 15 Janeiro 2021",
      price: 135,
      img: "https://m.media-amazon.com/images/I/619T0W3tfuL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Essencialismo: A disciplinada busca por menos",
      author: "by  Greg McKeown   | 5 Maio 2015",
      price: 69,
      img: "https://m.media-amazon.com/images/I/71HuZRl-XeL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "A ciranda das mulheres sábias: Ser jovem enquanto velha, velha enquanto jovem",
      author: "by Clarissa Pinkola Estés   | 28 Maio 2007",
      price: 289,
      img: "https://m.media-amazon.com/images/I/51dnXM9j0rL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Pai Rico, Pai Pobre Para Jovens: O que a escola não ensina sobre dinheiro ",
      author: " Robert T. Kiyosaki | 31 Agosto 2017",
      price: 80,
      img: "https://m.media-amazon.com/images/I/61qfGyk3CQL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Os segredos da mente milionária",
      author: "by  T. Harv Eker | 26 Julho 2006",
      price: 86,
      img: "https://m.media-amazon.com/images/I/81ZnJcgjCdL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Quem pensa enriquece",
      author: "by  Napoleon Hill  | 28 Maio 2018",
      price: 120,
      img: "https://m.media-amazon.com/images/I/61x4XUF8zvL._SY425_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "A psicologia financeira: lições atemporais sobre fortuna, ganância e felicidade ",
      author: "by  Morgan Housel  | 15 Março 2021",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81ehvI03NYS._SY425_.jpg",
      amount: 1,
    },
  ];
  
export default list;